### ISSUE TITLE
Place a go back button in a more logical location. 

### ISSUE THREAD

**Issue by lauraBaakman** [RUGSoftEng/Team-5#10]
Right now if I remember I already have an account and I don't want to register a new account I can go back, but to me the 'cancel and return to log in screen' is in an illogical place. I was looking for an arrow pointing to the left in the upper left corner of the window. 
![screenshot 2016-05-30 12 24 14 2](https://cloud.githubusercontent.com/assets/4301624/15647024/6b117bca-2661-11e6-951c-a02fad2f3821.png)

**Comment by sibrenvanvliet** [comment]
The 'SlimStampen' text in the upper left is actually clickable and takes you back to the login page, but we understand that this is not indicated. However, we would prefer not to disturb the aesthetic of the SlimStampen logo, and stay consistent with the yellow back button on the top right as already seen on the Create and Open pages. How does this look?

![backbutton](https://cloud.githubusercontent.com/assets/17131312/15704727/3707f14c-27ec-11e6-8e0e-8aec85e19228.jpg)

**Comment by sibrenvanvliet** [comment]
Disregard my earlier talk about aesthetics; we have now agreed on the design below being more intuitive and still very nice design-wise. This has been implemented in the branch 'improveuserexperience' :)

![registerbackbutton](https://cloud.githubusercontent.com/assets/17131312/15706881/2926f69a-27f6-11e6-91f8-47cd2ce059fd.jpg)
