### ISSUE TITLE
Some of the text in the change interface language modal is not translated

### ISSUE THREAD

**Issue by lauraBaakman** [RUGSoftEng/Team-5#12]
As you can see the following elements should be translated
![screenshot 2016-05-30 12 28 57](https://cloud.githubusercontent.com/assets/4301624/15647197/6b494cac-2662-11e6-95c9-6bdac63a12fd.png)
- The languages in the dropdown
- The `change interface text`
- The text on the `save settings button`

**Comment by ewerkema** [comment]
Same issue as #13
