### ISSUE TITLE
The your language settings have been saved menu is not translated to arabic

### ISSUE THREAD

**Issue by lauraBaakman** [RUGSoftEng/Team-5#13]
![screenshot 2016-05-30 12 30 54 2](https://cloud.githubusercontent.com/assets/4301624/15647184/5c44149e-2662-11e6-8b74-72c6d0a96847.png)

**Comment by ewerkema** [comment]
Whenever you see an English text in Arabic, that means this line isn't translated yet. We will have to wait before Hichem translates it :)

**Comment by sibrenvanvliet** [comment]
Hichem translated all missing strings to Arabic :)

![arabic](https://cloud.githubusercontent.com/assets/17131312/15772928/5bdee15e-2974-11e6-9fd7-26087dc6ad91.jpg)
