### ISSUE TITLE
Why can I even press the 'Create Dataset' button when I haven't added any items? 

### ISSUE THREAD

**Issue by lauraBaakman** [RUGSoftEng/Team-5#14]
![screenshot 2016-05-30 12 34 13 2](https://cloud.githubusercontent.com/assets/4301624/15647294/fbcbae28-2662-11e6-9e96-87e20d7d3a78.png)

**Comment by ewerkema** [comment]
This is what we achieve with Parsley, it will show the user what needs to be done. If someone presses the "Create dataset" button, he/she must think that its finished. In this case we will show the user what steps still need to be done.
