### ISSUE TITLE
The location of the 'create dataset' button feels strange

### ISSUE THREAD

**Issue by lauraBaakman** [RUGSoftEng/Team-5#15]
I expected the button next to the 'Add Item' button below the new items in the dataset. 
![screenshot 2016-05-30 12 36 57 2](https://cloud.githubusercontent.com/assets/4301624/15647328/34108952-2663-11e6-949c-2d73f3857aba.png)

**Comment by sibrenvanvliet** [comment]
Hedderik also commented about this; this is what the placement looks like in our version right now. Does this location seem more logical? Or would you still prefer it next to the 'Add item slot' button?

![createbuttonlocation](https://cloud.githubusercontent.com/assets/17131312/15706492/32f14d3a-27f4-11e6-89c1-9cd9c7d22f73.jpg)

**Comment by sibrenvanvliet** [comment]
We showed it to Hedderik today and he was pleased with the layout. I'll close this ticket for now.
