### ISSUE TITLE
'Create new dataset' should cover the whole of the 'new' dataset

### ISSUE THREAD

**Issue by lauraBaakman** [RUGSoftEng/Team-5#16]
![screenshot 2016-05-30 12 36 57 2](https://cloud.githubusercontent.com/assets/4301624/15647343/4aa8d692-2663-11e6-897b-da5a450c1799.png)
The current layout makes it look like the 'Name', 'Subject' and Language field are unrelated to the creating of the new dataset.

**Comment by sibrenvanvliet** [comment]
(Same image as in the issue about the placement of the green button.) Does this look better?

![createbuttonlocation](https://cloud.githubusercontent.com/assets/17131312/15706539/734a409e-27f4-11e6-98ed-8f810da6ca6e.jpg)

**Comment by lauraBaakman** [comment]
The caption over the meta data is a bit on the long side, looks strange to me. 

To me, having meta data on the left is more natural than having them on the right. As you work form left to right and I would do the meta data before the actual dataset.

**Comment by sibrenvanvliet** [comment]
We agree that it is more logical of a workflow to first give the dataset information, and then the actual items. This has been a one-or-the-other decision we've been discussing with Hedderik for a while, but we will now go with your preference. The metadata label is now also a bit shorter. Is this a design you would consider logical?

![createlayout](https://cloud.githubusercontent.com/assets/17131312/15707461/2700115a-27f9-11e6-9e0f-16c40694d925.jpg)

**Comment by sibrenvanvliet** [comment]
By the way, for the sake of consistency, we will also have the metadata fields on the left, on the Open page, which would then thus look like this:

![openlayout](https://cloud.githubusercontent.com/assets/17131312/15707800/f948dfce-27fa-11e6-8c2f-148cf6314878.jpg)

**Comment by lauraBaakman** [comment]
I'd align both buttons on the left. But I can also see an argument for putting the green one on the right.
