### ISSUE TITLE
The field descriptions 'Language' and 'Subject' are unclear

### ISSUE THREAD

**Issue by lauraBaakman** [RUGSoftEng/Team-5#17]
![screenshot 2016-05-30 12 36 57 2](https://cloud.githubusercontent.com/assets/4301624/15647409/993fdf3a-2663-11e6-97d9-791d049ed408.png)
It wasn't immediately clear to me how I should interpret the drop downs 'Language' and 'Subject', is 'Language' the language of the data set, the language I am trying to learn? Why is the number of options in the  'Language' drop down more limited than the number of options in the 'Subject' dropdown?

**Comment by sibrenvanvliet** [comment]
The problem with explaining these fields in a short label, is that they should be interpreted in different ways when using the program for language learning, and when learning subjects like biology or geography. We have now added tooltips as seen in the images below, triggered when hovering over the underlines labels. Do these make the intentions clear?

![tooltipsubject](https://cloud.githubusercontent.com/assets/17131312/15708955/3a50e5aa-2802-11e6-8dbe-c99d291a041a.jpg)

![tooltiplanguage](https://cloud.githubusercontent.com/assets/17131312/15708957/3f460b4e-2802-11e6-8aa6-8898ce6facdf.jpg)

**Comment by lauraBaakman** [comment]
That works :-D.
