### ISSUE TITLE
There is no go back button in the 'Create new dataset page'

### ISSUE THREAD

**Issue by lauraBaakman** [RUGSoftEng/Team-5#18]

**Comment by sibrenvanvliet** [comment]
There were actually already back buttons (clicking on 'SlimStampen' or the yellow button on the top right) but we realise that these were not very intuitive. In the branch 'improveuserexperience', it now looks like this:

![createbackbutton](https://cloud.githubusercontent.com/assets/17131312/15706816/c70665f4-27f5-11e6-951f-c9e07785a8ef.jpg)

**Comment by lauraBaakman** [comment]
Better.
