### ISSUE TITLE
After an error new dataset items are not validated.

### ISSUE THREAD

**Issue by lauraBaakman** [RUGSoftEng/Team-5#19]
The following flow:
1. Fill out name
2. Select a language
3. Select a Subject
4. Press 'Create dataset'
5. Fill out the first Question
6. Fill out first Answer
7. Fill out the second Question
8. Fill out the second Answer

Results in the following view where the second items, and any items after it are not validated.
![screenshot 2016-05-30 12 43 34 2](https://cloud.githubusercontent.com/assets/4301624/15647487/22c63e48-2664-11e6-948f-ae24063b767b.png)

**Comment by ewerkema** [comment]
Yes that is correct, we don't want to show the user that these items are incorrect when they create them. Its the same situation when you load the page. Then you also don't immediatly see if your fields are incorrect.
