### ISSUE TITLE
Give more information on the expected layout of a dataset file

### ISSUE THREAD

**Issue by lauraBaakman** [RUGSoftEng/Team-5#21]
To me, it is completely unclear which format the input files for a dataset should have.
![screenshot 2016-05-30 12 51 05 2](https://cloud.githubusercontent.com/assets/4301624/15647638/37ff9d76-2665-11e6-80f8-37e881c7538f.png)

**Comment by sdejong** [comment]
see #22

**Comment by sibrenvanvliet** [comment]
In the branch 'improveuserexperience', a tooltip is added which explains and shows an example of how the input file should be formatted:

![tooltipfiletype](https://cloud.githubusercontent.com/assets/17131312/15711326/c87bb00c-280d-11e6-98a0-3ca90b82b057.jpg)

**Comment by lauraBaakman** [comment]
Look good. I'd use what files can I open.

**Comment by sibrenvanvliet** [comment]
Changed the string to that.
