### ISSUE TITLE
Add some animation to your loading screen

### ISSUE THREAD

**Issue by lauraBaakman** [RUGSoftEng/Team-5#25]
The current 'saving dataset' give the impression that the application has frozen.

**Comment by ewerkema** [comment]
Do you preferr a loading image, or a loading message? For me saving datasets is very quick.. 

![slimstampen_loading](https://cloud.githubusercontent.com/assets/16745495/15707267/1b1e350c-27f8-11e6-9344-8e4cf93dddea.png)

**Comment by lauraBaakman** [comment]
I prefer a moving image with text. If that's not possible I'd go for an animation, I.e. Only the image. To me an animation shows that something is still happening, whereas static text doesn't distinguish between a frozen application and a long loading time.

**Comment by sibrenvanvliet** [comment]
Having text on the loading screen is an issue, because the internationalisation doesn't kick in until the loading is finished. We now have an animated spinner image, and Hedderik liked it, because it keeps moving so that the user knows that the program didn't lock up.

**Comment by lauraBaakman** [comment]
That is a perfectly valid reason not have text.
