### ISSUE TITLE
Flickering white page

### ISSUE THREAD

**Issue by lauraBaakman** [RUGSoftEng/Team-5#5]
Clicking on "SlimStampen" in the upper left corner when on `index.html` gives a white screen before the page is loaded again.

**Comment by sdejong** [comment]
Isn't this happening at all page transitions? There is a white flash before the loading message shows. We think this is a Electron problem.

**Comment by lauraBaakman** [comment]
That seems like a good reasong to

**Comment by lauraBaakman** [comment]
In that case you mark the issue as wontfix and close it.
