### ISSUE TITLE
Give the background of the images in the log in screen an alpha version of 0

### ISSUE THREAD

**Issue by lauraBaakman** [RUGSoftEng/Team-5#9]
![screenshot 2016-05-30 12 21 38](https://cloud.githubusercontent.com/assets/4301624/15646961/166a6c94-2661-11e6-9b4c-6d86def3ac30.png)

**Comment by ewerkema** [comment]
![alphazerologo](https://cloud.githubusercontent.com/assets/16745495/15759652/f68014e0-290f-11e6-9d82-940edb68141e.png)
